# grpc server
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geeter-deployment
  labels:
    app: geeter
spec:
  selector:
    matchLabels:
      app: geeter
  replicas: 1
  template:
    metadata:
      labels:
        app: geeter
    spec:
      containers:
      - name: geeter
        image: 192.168.0.240:5000/greeter_server
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-server
spec:
  selector:
    app: geeter
  ports:
  - port: 50051
    targetPort: grpc

# api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeterapi-deployment
  labels:
    app: greeterapi
spec:
  selector:
    matchLabels:
      app: greeterapi
  replicas: 1
  template:
    metadata:
      labels:
        app: greeterapi
    spec:
      containers:
      - name: greeterapi
        image: 192.168.0.240:5000/greeter_api
        imagePullPolicy: Always
        ports:
        - name: gapi-service
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: gapi-service
spec:
  type: NodePort
  selector:
    app: greeterapi
  ports:
  - port: 9090
    targetPort: gapi-service