apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: kube-system
  labels:
    app: default-backend
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: default-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: default-backend
  name: default-backend
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
        cluster: none
      name: default-backend
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: registry-vpc.cn-hangzhou.aliyuncs.com/ytzx2020/default-backend:1.0
        volumeMounts:
        - mountPath: /var/www/html
          name: html
      imagePullSecrets:
        - name: ytzx
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: default-backend
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: default-backend
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfsroot/nginx
    server: 172.16.153.180