apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: tcp
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      containers:
      - name: redis
        imagePullPolicy: IfNotPresent
        image: redis:5.0.7
        volumeMounts:
        - mountPath: /usr/local/etc/redis/redis.conf
          name: config 
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf
