apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    bind 0.0.0.0
    port 6379
    save ""
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: tcp
    nodePort: 30628
  selector:
    app: redis
    cluster: none
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        cluster: none
      name: redis
    spec:
      containers:
      - name: redis
        imagePullPolicy: IfNotPresent
        image: redis:6.0.8
        volumeMounts:
        - mountPath: /usr/local/etc/redis/redis.conf
          name: config
      volumes:
        - name: config
          configMap:
            name: redis-config
            items:
            - key: redis-config
              path: redis.conf
