apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
  - name: tcp
    port: 27017
    targetPort: 27017
  selector: 
    app: mongo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      containers:
      - name: mongo
        imagePullPolicy: IfNotPresent
        image: mongo:4.2.1
        ports: 
        - containerPort: 27017
        volumeMounts: 
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        hostPath:
          path: /data/mongodb/db
