apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: jaeger-agent
spec:
  template:
    metadata:
      labels:
        app: jaeger-agent
      name: jaeger-agent
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.16.0
        ports:
        - containerPort: 5775
          protocol: UDP
          name: udp-5775
        - containerPort: 6831
          protocol: UDP
          name: udp-6831
        - containerPort: 6832
          protocol: UDP
          name: udp-6832
        - containerPort: 5778
          protocol: TCP
          name: tcp-5778
        args: ["--reporter.type=grpc", "--reporter.grpc.host-port=dns:///jaeger-collector:14250"]
---        
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent-svc
  labels:
    app: jaeger-agent-svc
spec:
  ports:
  - name: udp-6831
    port: 6831
    protocol: UDP
    targetPort: 6831
    nodePort: 30381
  selector:
    app: jaeger-agent
  type: NodePort        