persistence:
  enabled: true
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  existingClaim: pvc-loki
config:
  limits_config:
    ingestion_burst_size_mb: 20

  table_manager:
    retention_deletes_enabled: true
    retention_period: 672h