config:
  lokiAddress: http://loki:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - docker: {}
      - multiline:
            firstline: '^time="\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}"'
            max_wait_time: 2s

