kind: Service
apiVersion: v1
metadata:
  name: mysql-datacenter
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 0
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-datacenter
subsets:
  - addresses:
      - ip: "172.16.0.101"
    ports:
      - port: 3306
        name: mysql
---
kind: Service
apiVersion: v1
metadata:
  name: mssqlserver-core
spec:
  ports:
    - name: mssqlserver
      protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 0
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mssqlserver-core
subsets:
  - addresses:
      - ip: "172.18.181.177"
    ports:
      - port: 1433
        name: mssqlserver