apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq
subjects:
- kind: ServiceAccount
  name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: 5672
    name: port-5672
    protocol: TCP
    targetPort: 5672
    nodePort: 30672 
  - port: 4369
    name: port-4369
    protocol: TCP
    targetPort: 4369    
  - port: 5671
    name: port-5671
    protocol: TCP
    targetPort: 5671    
  - port: 15672
    name: port-15672
    protocol: TCP
    targetPort: 15672    
  - port: 25672
    name: port-25672
    protocol: TCP
    targetPort: 25672    
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq  
    version: v1.0.0
spec:
  selector:    
    matchLabels:
      app: rabbitmq
      version: v1.0.0
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        version: v1.0.0
    spec:
      serviceAccountName: rabbitmq
      volumes: 
      - name: tz-config
        hostPath:
          path: /etc/localtime
      - name: configmap  
        configMap:
          name: cm-rabbitmq
      - name: config  
        emptyDir: {}
      initContainers:
        - name: copy-rabbitmq-config
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'cp /configmap/* /etc/rabbitmq; rm -f /var/lib/rabbitmq/.erlang.cookie']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /etc/rabbitmq 
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8.1-management
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5672
            name: port-5672
          - containerPort: 4369
            name: port-4369
          - containerPort: 5671
            name: port-5671
          - containerPort: 15672
            name: port-15672
          - containerPort: 25672
            name: port-25672
        env:
          - name: AUTOCLUSTER_TYPE
            value: "k8s"
          - name: AUTOCLUSTER_DELAY
            value: "10"
          - name: AUTOCLUSTER_CLEANUP
            value: "true"
          - name: RABBITMQ_DEFAULT_USER
            value: guest                        # 连接rabbit的账号
          - name: RABBITMQ_DEFAULT_PASS
            value: guest                       #连接rabbit的密码
          - name: HOSTNAME
            valueFrom:
             fieldRef:
              fieldPath: status.podIP
          - name: MY_POD_IP
            valueFrom:
             fieldRef:
              fieldPath: status.podIP
          - name: CLEANUP_INTERVAL
            value: "60"
          - name: CLEANUP_WARN_ONLY
            value: "false"
          - name: K8S_SERVICE_NAME
            value: "rabbitmq"
          - name: K8S_ADDRESS_TYPE
            value: "hostname"
          - name: K8S_HOSTNAME_SUFFIX
            value: ".$(K8S_SERVICE_NAME)"
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
             secretKeyRef:
              name: erlang.cookie
              key: erlang.cookie
        resources:       
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: config
          mountPath: /etc/rabbitmq
---      
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rabbitmq
  labels:
    app: rabbitmq
data:
  enabled_plugins: |
    [
      rabbitmq_management
    ].
  rabbitmq.conf: |
    ## RabbitMQ configuration
    ## Ref: https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example   
    ## via a loopback interface (e.g. localhost)
    loopback_users.guest = false
    loopback_users.ctc = false
  definitions.json: |
    {
      "users": [
        {
          "name": "ctc",
          "password": "Yxkj11!!$$",
          "tags": "administrator"
        }
      ],
      "permissions": [
        {
          "configure": ".*",
          "read": ".*",
          "user": "ctc",
          "vhost": "ctc",
          "write": ".*"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        },
        {
          "name": "ctc"
        }
      ]
    }      