apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-server
spec:
  hosts:
  - grpc-server
  http:
  - route:
    - destination:
        host: grpc-server
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grpc-server
spec:
  host: grpc-server
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  